name: Automatic project deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checking and copying code 
        uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Installing dependencies
        run: npm install

      - name: Launching Pre-deploy
        run: npm run predeploy

      - name: Configure Git Author
        run: |
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"

      - name: Запуск Деплоя (Deploy)
        run: npm run deploy
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
